PHP_VERSION=8.1
OPENCART_CLI_VERSION=1.0.0
OPENCART_VERSION=4.0.1.1
OPENCART_USERNAME=admin
OPENCART_EMAIL=email@example.com
OPENCART_PASSWORD=admin
OPENCART_DOMAIN=opencart.docker
OPENCART_ADMIN=backoffice
